# Mist Insight Version
VERSION: "2.4.1"

# Mist Registry
MIST_REGISTRY: ""

# Mist Hostname
MIST_HOSTNAME: ""

# TLS + JKS
MIST_TLS_CRT: ""
MIST_TLS_KEY: ""
MIST_CA_PEM: ""
MIST_KEYSTORE_JKS: ""
MIST_KEYSTORE_PASSWORD: ""

# Keycloak
KEYCLOAK_VERSION: "keycloak:26.0.7"
KEYCLOAK_DATABASE_PASSWORD: ""
KEYCLOAK_ADMIN_PASSWORD: "mistech_admin"
KEYCLOAK_CLIENT_ID: ""
KEYCLOAK_CLIENT_SECRET: ""

# Postgres
MIST_DATABASE_PASSWORD: ""

# Redis
REDIS_PASSWORD: ""

# Rabbitmq
RABBITMQ_PASSWORD: ""

# Opensearch
OPENSEARCH_PASSWORD: ""

# S3
S3_REGION: "ru-central-1"
S3_ACCESS_KEY: ""
S3_SECRET_KEY: ""

# External
EXTERNAL_POSTGRES_HOST: ""
EXTERNAL_POSTGRES_PORT:
EXTERNAL_S3_HOST: ""
EXTERNAL_S3_PORT:

# Microservices
PERFORMANCE_SERVICE_CPU_LIMIT: "2"
PERFORMANCE_SERVICE_MEMORY_LIMIT: 4096M
PERFORMANCE_SERVICE_CPU: "1"
PERFORMANCE_SERVICE_MEMORY: 2048M
PERFORMANCE_SERVICE_JAVA_OPTS: "-Xmx4000m"
EFFECTIVE_SERVICE_CPU: "0.25"
EFFECTIVE_SERVICE_MEMORY: 1024M
EFFECTIVE_SERVICE_JAVA_OPTS: "-Xmx950m"
