####### Mist #######
# Mist DB

# JKS
apiVersion: v1
kind: Secret
metadata:
  name: jks-secret
  namespace: mist-insight
type: Opaque
data:
  # jks
  keystore.jks: {{ .Values.MIST_KEYSTORE_JKS }}
  ca.pem: {{ .Values.MIST_CA_PEM }}
---
####### Redis #######
# Redis Password
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: mist-insight
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.REDIS_PASSWORD }}
---
####### Keycloak #######
# Keycloak DB
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgres-secret
  namespace: mist-insight
type: Opaque
stringData:
  POSTGRES_DB: keycloak
  POSTGRES_USER: keycloak
  POSTGRES_PASSWORD: {{ .Values.KEYCLOAK_DATABASE_PASSWORD }}
---
# TLS
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: mist-insight
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.MIST_TLS_CRT }}
  tls.key: {{ .Values.MIST_TLS_KEY }}
---
# Keycloak Admin User
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: mist-insight
type: Opaque
stringData:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.KEYCLOAK_ADMIN_PASSWORD }}
---
# Keycloak SPI
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-spi-secret
  namespace: mist-insight
type: Opaque
stringData:
  spi.properties: |
    app.rabbit.host=rabbitmq
    app.rabbit.port=5672
    app.rabbit.user=mistech_srvs_conn
    app.rabbit.password={{ .Values.RABBITMQ_PASSWORD }}
    app.rabbit.routing-key=binding.syslog
    app.rabbit.virtual-host=mist_srvs_vhost
    app.rabbit.exchange-name=direct.audit
    app.rabbit.queue=queue.syslog
    app.rabbit.ssl.enabled=true
    app.rabbit.ssl.key-store-path=/etc/secret/keystore.jks
    app.rabbit.ssl.key-store-type=JKS
    app.rabbit.ssl.key-store-pass={{ .Values.MIST_KEYSTORE_PASSWORD }}
    app.rabbit.ssl.trust-store-path=/etc/secret/keystore.jks
    app.rabbit.ssl.trust-store-type=JKS
    app.rabbit.ssl.trust-store-pass={{ .Values.MIST_KEYSTORE_PASSWORD }}
